server_hostname: "$SERVER_HOSTNAME"
http_path: "$HTTP_PATH"
personal_access_token: "$PERSONAL_ACCESS_TOKEN"
catalog_name: "$CATALOG_NAME"
schema_name: "$SCHEMA_NAME"
table_prefix: "$TABLE_PREFIX"
non_ascii_catalog_name: "$NON_ASCII_CATALOG_NAME"
non_ascii_schema_name: "$NON_ASCII_SCHEMA_NAME"
staging_volume_name_prefix: "$STAGING_VOLUME_NAME_PREFIX"
